# Pre-commit is installed by poetry alongside black, isort, flake8
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black --config pyproject.toml
    language: system
    require_serial: true
    types: [python]
  - id: isort
    name: isort
    entry: poetry run isort --settings-path pyproject.toml
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: poetry run flake8 --config .flake8
    language: system
    types: [python]