source_doc: "Master_Thesis.pdf"
rag_mode: "auto-merging retrieval"
llm_openai_model: "gpt-4o-mini"
embed_model: "BAAI/bge-small-en-v1.5"
chunk_sizes: [2048, 512, 128]
similarity_top_k: 6
rerank_model: "cross-encoder/ms-marco-MiniLM-L-2-v2"
rerank_top_n: 2
