name: Update deploy branch

on:
  push:
    branches:
      - master

jobs:
  update-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install Poetry and export plugin
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH
          poetry self add poetry-plugin-export

      - name: Generate requirements.txt
        run: |
          poetry export --format requirements.txt --output spaces/requirements.txt --without-hashes

      - name: Switch to deploy branch
        run: |
          git fetch origin
          git switch deploy

      - name: Updated deploy branch
        run: |

          git checkout master -- src/mythesis_chatbot/rag_setup.py
          git checkout master -- src/mythesis_chatbot/evaluation.py
          git checkout master -- src/mythesis_chatbot/utils.py
          git checkout master -- src/mythesis_chatbot/__init__.py
          git checkout master -- scripts/app.py
          git checkout master -- spaces/requirements.txt
          git checkout master -- spaces/welcome_message.md
          git checkout master -- spaces/README.md
          git checkout master -- configs/
          mv spaces/requirements.txt requirements.txt
          mv spaces/README.md README.md


          # Commit changes if there are any
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update deploy branch from master"
            git push origin deploy
          fi
